name: startbioinfo
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - fastqc
  - multiqc
  - bwa
  - samtools
  - bcftools
  - freebayes
  - picard
  - seqtk
  - wget
  - curl
